name: docker deploy

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          target: prod
          tags: ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:latest
